name: madmeesh
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://msawangwan.github.io" # the base hostname & protocol for your site
markdown: kramdown
collections:
    articles:
        output: true
        permalink: /article/:path/
